version: "3"
services:
  client:
    image: "pujabapat/multi-client-10-14"
    mem_limit: 128m
    hostname: client
  server:
    image: "pujabapat/multi-server-10-14"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "pujabapat/multi-worker-10-14"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "pujabapat/multi-nginx-10-14"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"



      
 
# # Dockerrun.aws.json
#  {
#     "AWSEBDockerrunVersion": 2,
#     "containerDefinitions": [{
#         "name": "client",
#         "image": "pujabapat/multi-client",
#         "hostName": "client",
#         "essential": false
#     },
#     {
#         "name": "server",
#         "image": "pujabapat/multi-server",
#         "hostname": "api",
#         "essential": false
#     },
#     {
#         "name": "worker",
#         "image": "pujabapat/multi-worker",
#         "hostname": "worker",
#         "essential": false
#     },
#     {
#         "name": "ngnix",
#         "image": "pujabapat/multi-ngnix",
#         "hostname": "ngnix",
#         "essential": true,
#         "portMappings": [
#             {
#                 "hostPort": 80,
#                 "containerPort": 80
#             }
#         ],
#         "links": ["client", "server"]
#     }
# ]
# }

